
-- 创建展品数据表
#   `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
CREATE TABLE `artwork`(
  `id` INT(11) NOT NULL ,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `description` longtext NOT NULL,
  `imgPath` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `hot` int(11) NOT NULL DEFAULT '0',
  `time` VARCHAR(255) NOT NULL,
   `videoPath`  VARCHAR(255) not null default '../video/video.mp4',
   `uploadingTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `artwork`
    ADD PRIMARY KEY (`id`);

ALTER TABLE `artwork`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (1, '安喜宫绣佛像', '工艺', '明·成化·《安喜宫绣佛像》绣品。长93.2cm，宽31cm。作于成化七年。安喜宫，是成化年间万贵妃居住的宫殿。她于成化二年进封皇贵妃时开始居住，一直居住至成化二十三年春。万氏（1430-1487），也叫万贞儿，青州诸城人。明宪宗朱见深之妃，颇得宠爱，世称万贵妃。绣，是我囯特有的一种手工制作工艺，用针将彩色的线缝在绸或布上构成图案、花纹和文字。又指绣成的物品。', '../img/工艺/安喜宫绣佛像.jpg', '上海博物馆', 0, '明成化七年', '../video/video.mp4', '2019-07-23 20:59:02');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (2, '鲍天成透雕浮槎犀角杯', '工艺', '犀角杯为一老者坐独木舟，划行在水浪之中，有“天成”篆书印款。艺人采用圆雕、透雕、浮雕和浅刻相结合的技法，使整个作品层次丰富，雕刻精湛。鲍天成，明代吴县（今江苏苏州）人，牙角雕名匠，他的犀角雕被誉为“吴中绝技”。', '../img/工艺/鲍天成透雕浮槎犀角杯.jpg', '上海博物馆', 0, '明末清初', '../video/video.mp4', '2019-07-23 20:59:02');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (3, '缂丝花鸟图', '工艺', '缂丝又称刻丝，是中国汉族丝绸艺术品中的精华。这是一种经彩纬显现花纹，形成花纹边界，具有犹如雕琢缕刻的效果，且富双面立体感的丝织工艺品。缂丝的编织方法不同于刺绣和织锦。它采用“通经断纬”的织法，而一般锦的织法皆为“通经通纬”法，即纬线穿通织物的整个幅面。缂丝能自由变换色彩，因而特别适宜制作书画作品。缂织彩纬的织工须有一定的艺术造诣。缂丝织物的结构则遵循“细经粗纬”、“白经彩纬”、“直经曲纬”等原则。即：本色经细，彩色纬粗，以纬缂经，只显彩纬而不露经线等。由于彩纬充分覆盖于织物上部，织后不会因纬线收缩而影响画面花纹的效果。', '../img/工艺/缂丝花鸟图.jpg', '上海美术馆', 0, '清 乾隆', '../video/video.mp4', '2019-07-23 20:59:02');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (4, '﻿全金石', '金石', '簋是一种古代食器，用来盛装煮熟的稻、粱等食物，犹如现在的饭盆，饮宴时使用。它又是一种重要的礼器，盛行于商、周时期，使用者一般为王侯贵族。是由当时称作“金”的青铜铸成。簋与老百姓无缘，那时穷苦百姓使用的大多是陶器。簋和鼎配套使用，盛装上食物、牺牲等供奉在神坛上祭祀天地祖先。周代礼制中对鼎用簋的使用有严格规定：天子九鼎八簋，诸侯七鼎六簋，大夫五鼎四簋………“九鼎八簋”是最高礼仪，只有周天子才能享用。', '../img/金石/镶嵌画像纹壶.jpg', '故宫博物馆', 0, '1904', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (5, '剑经', '书画', '唐·杜牧《题宣州开元寺水阁，阁下宛溪，夹溪居人》。六朝：指东吴、东晋、宋、齐、梁、陈。这两句大意是：六朝文物早已不见，只有草色连空；那天淡云闲的景象，倒是古今相同。开元寺是宣州(今安徽宣城)的名胜，诗人任宣州团练判官时，常来此玩赏。', '../img/书画/清蒋廷锡芍药图轴.jpg', '上海博物馆', 1, '2019', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (6, '世界无双石', '金石', '簋是一种古代食器，用来盛装煮熟的稻、粱等食物，犹如现在的饭盆，饮宴时使用。它又是一种重要的礼器，盛行于商、周时期，使用者一般为王侯贵族。是由当时称作“金”的青铜铸成。簋与老百姓无缘，那时穷苦百姓使用的大多是陶器。簋和鼎配套使用，盛装上食物、牺牲等供奉在神坛上祭祀天地祖先。周代礼制中对鼎用簋的使用有严格规定：天子九鼎八簋，诸侯七鼎六簋，大夫五鼎四簋………“九鼎八簋”是最高礼仪，只有周天子才能享用。', '../img/金石/广东寿字.jpg', '西安历史博物馆', 0, '1904', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (7, '纯铜酒壶', '金石', '唐代大诗人白居易有一首诗,题目叫《宿紫阁山北村》,诗中写到:''晨游紫阁峰,暮宿山下村。村老见余喜,为余开一樽。''此诗比较通俗,诗的前两句一看都明白,后两句的意思是:山村老人见了我后很高兴,特意为我办了一桌酒席。诗中的''樽'',指的是盛酒器,相当于现代的酒壶。尊,古时又写樽、鐏。', '../img/金石/束腰爵.jpg', '中国国家博物馆', 0, '1967', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (8, '莲花玉', '陶瓷', '莲花玉，又名琅玕。产自舟山普陀山南海观音座下的莲花洋上！玉质或漆黑生亮、或黄绿相间，光滑细腻，包浆圆润，玉质感极佳，密度3以上，硬度7以上，硬度和密度超新疆和田玉，接近翡翠，是2014年2月在舟山海域刚发现的一种不可多得的新玉种！因其数量非常稀缺，尤显珍贵！', '../img/陶瓷/青釉莲瓣纹壶.jpg', '故宫博物馆', 0, '1924', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (9, '红陶人', '陶瓷', '红褐陶人。残高4.2厘米，陕西扶风案板，仰韶文化晚期。人形浮雕陶壶。高34.4厘米，青海乐都柳湾，马厂类型。红陶人头像，该藏品高12.5厘米。头像中空,额前至脑后塑有半圈凸起的带状泥条，眉微隆起眼、嘴镂空成横条状，鼻呈三角形，下颚短小，向前略凸，两耳耳垂各有一穿孔，颈部粗壮。', '../img/陶瓷/郊坛下官窑瓶.jpg', '甘肃博物馆', 0, '1760', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (10, '和田玉', '陶瓷', '岫岩玉广义上可以两类，一类是老玉，老玉中的籽料称作河磨玉，属于透闪石玉，其质地朴实、凝重、色泽淡黄偏白，是一种珍贵的璞玉；另一类是岫岩碧玉，其质地坚实而温润，细腻而圆融，多呈绿色至湖水绿，其中以深绿、通透少瑕为珍品。', '../img/陶瓷/青釉刻花双系鸡首壶.jpg', '陕西博物馆', 0, '1605', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (11, '会意微笑佛头', '陶瓷', '佛教在西域几百年的发展中创造了辉煌灿烂的艺术，西域佛教遗迹中的石窟造像就是其中最为精彩的部分。佛头是20世纪初，在巴楚县发掘托库孜萨来佛寺遗址时发现的，体现了印度风格与犍陀罗形制的融合，其中还可以看到明显的西域本地人的特征。', '../img/陶瓷/黄釉陶狗.jpg', '四川博物馆', 0, '1729', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (12, '马状茶壶', '陶瓷', '经我仔细观察了解，一般平民百姓使用的马黛茶壶大多是竹筒或葫芦挖空制成的，壶上没有什么装饰。  而高档的茶壶则是一种艺术品，做工精致，有金属模压的，有硬木雕琢的，有葫芦镶边的，也有皮革包裹的，还有牛角磨制的，形状千奇百怪，以怪为贵。  壶的外壁刻有马头、鹦鹉、山水、花鸟、天使等各种图案，有的被视为''带来好运''的祝福，有的象征''怀念''或''友谊''。', '../img/陶瓷/宜兴陈曼生制半瓦当式紫砂壶.jpg', '四川博物馆', 0, '1613', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (13, '耳玦', '陶瓷', '玦是一种开口的环状装饰物，一般呈扁平体，圆形，中心有孔，佩戴于耳上。    新石器时代，人们已经将玦用作耳饰。各地的新石器文化遗址中，均发现此种饰物，出土位置大多在墓主人耳际。但这些遗址基本分布于长江流域中下游地区及华南地区，而在黄河流域则少见。商周以后，中原地区及北方地区的居民，也喜欢在耳部佩戴这种饰物。北京琉璃河西周燕国墓和山西侯马上马村春秋中晚期墓葬都出土过玉玦。', '../img/陶瓷/清乾隆胭脂红彩缠枝龙纹瓶.jpg', '故宫博物馆', 0, '1579', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (14, '貔貅摆件', '陶瓷', '貔貅拼音是pí xiū，别称''辟邪、天禄''，是中国古书记载和民间神话传说的一种凶猛的瑞兽。中国古代风水学者认为貔貅是转祸为祥的吉瑞之兽。从古至今，上至帝王、下至百姓都极度注重收藏和佩戴貔貅，传说貔貅除了开运、辟邪的功效之外，还有镇宅、化太岁、促姻缘等作用。中国传统有装饰''貔貅''的习俗，貔貅寓意丰富，人们相信它能带来欢乐及好运，古时候人们常用貔貅来作为军队的称呼。', '../img/陶瓷/黄釉陶狗.jpg', '四川博物馆', 0, '1725', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (15, '人面铜壶', '金石', '花隔铜壶，露晞金掌，都门十二清晓。帝里风光烂漫，偏爱春杪。烟轻昼永，引莺啭上林，鱼游灵沼。巷陌乍晴，香尘染惹，垂杨芳草。因念秦楼彩凤，楚观朝云，往昔曾迷歌笑。别来岁久，偶忆欢盟重到。人面桃花，未知何处，但掩朱扉悄悄。尽日伫立无言，赢得凄凉怀抱。', '../img/金石/天王石像.jpg', '天津博物馆', 0, '2016', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (16, '战国短剑', '金石', '短剑，是长度比较短的剑，一般在25厘米到60厘米之间，太短则宜称为匕首，太长则不宜称为短剑。中国古代标准剑长为三尺，故名''三尺剑''。 《史记·高祖本纪》：''吾以布衣提三尺剑取天下，此非天命乎？'' 唐·杜甫《重经昭陵》诗：''风尘三尺剑，社稷一戎衣。''古代''三尺''长度不一，从69厘米到96厘米不等，凡短于69厘米的剑皆应称为短剑。', '../img/金石/古父己卣.jpg', '西安历史博物馆', 0, '1687', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (17, '双虎玉', '金石', '战国中山王厝墓出土的双虎玉佩，材质为灰黄色黄玉，双虎连体，近似璜形。一面浮雕边棱、体表满雕蚕纹和丝纹，另一面勾有线稿草样，但未经雕刻，应是专门为中山王厝雕刻的明器。', '../img/金石/镶嵌画像纹壶.jpg', '重庆博物馆', 0, '1720', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (18, '祭孔礼乐器', '金石', '敦礼重义，为世人所称道。古代的祭祀名目繁多，祭祀要有专器，故古代的礼器也很多。祭孔礼器分为两类，一为皇帝御赐，仅供陈列；一为祭祀实用的礼器。帝王御赐祭孔的礼器，最早记载于汉章帝元和二年（85年），章帝过鲁祭孔子，留太尊、牺尊、象尊、山尊、雷尊、明水瓶共六事。', '../img/金石/家爵.jpg', '天津博物馆', 0, '1805', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (19, '竹筒三字经', '字画', '由竹片或木片制成的竹简是我国古代最早的书籍形式之一，随着纸张的发明运用，简牍消失在人们的视野中，现在人们只有在博物馆和影视作品中才能见到这种古老的书籍形式。《三字经》，是中国的传统启蒙教材。在中国古代经典当中，《三字经》是最浅显易懂的读本之一。《三字经》取材典范，包括中国传统文化的文学、历史、哲学、天文地理、人伦义理、忠孝节义等等。', '../img/书画/清金农梅花图轴.jpg', '山东博物馆', 0, '1558', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (20, '佛教心经', '字画', '观自在菩萨，行深般若波罗蜜多时，照见五蕴皆空，度一切苦厄。舍利子，色不异空，空不异色，色即是空，空即是色，受想行识， 亦复如是。舍利子，是诸法空相，不生不灭， 不垢不净，不增不减。是故空中无色，无受想行识，无眼耳鼻舌身意，无色声香味触法， 无眼界，乃至无意识界，无无明，亦无无明尽，乃至无老死，亦无老死尽。无苦集灭道， 无智亦无得，以无所得故。', '../img/书画/清弘仁疏泉洗砚图卷.jpg', '陕西博物馆', 0, '1737', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (21, '葡萄纹花鸟银香囊', '工艺', '葡萄花鸟纹银香囊，为西安何家村出土，外壁直径4.6、壁厚0.05、外层机环直径3.9、宽0.39、内层机环直径3.4、宽0.3厘米；金香盂直径2.8厘米；链长7.5厘米、重36克；香囊外壁用银制，呈圆球形，通体镂空，以中部水平线为界平均分割形成两个半球形，上下球体之间，一侧以钩链相勾合，一侧以活轴相套合。', '../img/工艺/鸟纹玉璧.jpg', '中国国家博物馆', 1, '1944', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (22, '德武抗战印象', '字画', '他的''德系''部队，就不得不提到他的淞沪会战，虽然最终以中国惨败而告终。但从会战开始直到蒋介石下令撤退，罗卓英指挥部队与日军反复争夺罗店、浏河一带。白天，日军在飞机、坦克、大炮的配合下夺取阵地；夜晚，罗部将阵地夺回，战斗非常艰苦和激烈，官兵伤亡惨重。', '../img/书画/清郑燮竹石兰花图轴.jpg', '中国国家博物馆', 0, '1796', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (23, '湘绣', '工艺', '湘绣是中国四大名绣之一，是以湖南长沙为中心的带有鲜明湘楚文化特色的湖南刺绣产品的总称，它起源于湖南的民间刺绣，吸取了苏绣和粤绣的优点而发展起来，已经有2000多年历史。湘绣以着色富于层次、绣品若画为特点，民间有苏猫、湘虎之说。湘绣狮虎毛纹刚健直竖，眼球有神，几可乱真，已发展到异色、异形、异面的双面全异绣。', '../img/工艺/缂丝花鸟图.jpg', '长沙博物馆', 1, '1536', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (24, '商代飨戚', '金石', '器身四壁皆出棱脊，给人以凝重之感，提梁置于器腹正面两侧，与一般在两腹侧者不同，全器以纤细的云雷纹为地，饰不同形态的动物纹饰六种，腹部为大饕餮，双目特大，盖沿和圈足各饰夔龙一周，器沿饰长尾凤鸟纹一周，盖顶亦饰饕餮纹，鋬饰长体夔龙，鋬首作龙首形，形制庄重，纹饰华丽，是商代晚期青铜器的珍品。', '../img/金石/错金银鸟兽形壶.jpg', '西安博物馆', 0, '1930', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (25, '开元通宝铜钱', '金石', '开元通宝为唐代货币。钱币在唐代始有''通宝''。唐初沿用隋五铢，轻小淆杂。唐高祖武德四年，为整治混乱的币制，废隋钱，效仿西汉五铢的严格规范，开铸''开元通宝''，取代社会上遗存的五铢。最初的''开元通宝''由书法家欧阳询题写，面文''开元通寳''，形制仍沿用秦方孔圆钱，规定每十文重一两，每一文的重量称为一钱，而一千文则重六斤四两。', '../img/金石/秦公镈.jpg', '中国国家博物馆', 0, '1711', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (26, '梅花帖', '字画', '在国画中，梅花通常有双钩法、没骨法两种方法。双勾法一般适用于刻画圈梅，而没骨法则常用于画红梅、腊梅等。双勾法用笔要有力道，有骨气，而没骨法则要把握好笔上颜色与水分的比例。梅花的花蕊处生长着细长的蕊丝，蕊丝上面还有一个比芝麻还小的小点，为蕊头。画花蕊时要挺住手腕，线条要细挺刚劲，不能粗、不能弱，每一条线都要气贯始终，功力到位。', '../img/书画/清赵之谦菊花图轴.jpg', '四川博物馆', 0, '2012', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (27, '青釉花插', '工艺', '卷的荷叶，亭亭玉立，含苞绽放，它那曼妙的身姿，天青的蓝色，构成人与自然和谐一体。别具风格的它，温厚而内敛，端庄而优雅，质朴而古拙，有着强烈的民族艺术倾向，透射出一种纯粹的民族精神。它既没有唐代陶瓷的雍容华贵，也没有明清瓷器的繁缛纤细，既不乖巧，也不矫饰，更不哗宠，而是简洁素雅，以型取胜，带给人们经久不绝的视觉享受。充分体现了宋人文雅崇尚的淡雅风格，也凸显了物雅何虽大的最高意境，同时也印证了汝窑无大器的传统观点。', '../img/工艺/竹根雕蝠桃盂.jpg', '西安历史博物馆', 0, '1521', '../video/video.mp4', '2019-07-23 20:59:19');
INSERT INTO javaweb.artwork (id, name, type, description, imgPath, location, hot, time, videoPath, uploadingTime) VALUES (28, '兰亭集序', '字画', '王羲之的《兰亭序》是中国书法上的''至宝'',尤以''天下第一行书''之名声闻天下人们都知道它的诞生过程,可是很少有人知道,这件旷世之作在伴随它的主人在浙东的一座大山里度过了他人生的最后岁月,就开始了传奇的流转历程,最后被皇家收入宫内。然而,这一风华绝代的书法传奇,自唐高宗之后逐渐消失于人们的视线，它扑朔迷离的去向牵动着无数人的情感......', '../img/书画/清虚谷枇杷图轴.jpg', '山东博物馆', 0, '1731', '../video/video.mp4', '2019-07-23 20:59:19');